2021-11-28 12:25:28,baseApi(line:95),ERROR|Traceback (most recent call last):
  File "/Users/shenyuming/PycharmProjects/autotest/common/baseApi.py", line 90, in define_api_assert
    assert result == exp_result
AssertionError

